# Configure main menu and social menu

[[main]]
    identifier = "categories"
    name       = "分类 | Categories"
    url        = "/categories/"
    weight     = 4

    [main.params]
        icon = "categories"

[[main]]
    identifier = "tags"
    name       = "标签 | Tags"
    url        = "/tags/"
    weight     = 5

    [main.params]
        icon = "tag"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/Drawn123"

    [social.params]
        icon = "brand-github"
